#!/bin/bash

# Setting up the prompt
[[ -f /usr/share/git/git-prompt.sh ]] && . /usr/share/git/git-prompt.sh
PS1='\n\[\e[91m\]\u \[\e[35m\]\h \[\e[33m\]\w\[\e[36m\]`__git_ps1`\[\e[91m\]\n$ \[\e[31m\]'
