#!/bin/zsh
spectacle -bn $@ -o ~/Pictures/Screenshot-$(date "+%Y.%m.%d-%H.%M.%S").png;
xclip -selection clipboard -target image/png -i ~/Pictures/Screenshots/Screenshot-$(date "+%Y.%m.%d-%H.%M.%S").png;
paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga