# Load the shell dotfiles, and then some:
# * ~/.sh/path can be used to extend `$PATH`.
for file in ~/.bash/{exports,path}; do
	if [[ -r "$file" ]] && [[ -f "$file" ]]; then
		# shellcheck source=/dev/null
		source "$file"
	fi
done
unset file

[[ -f ~/.bashrc ]] && . ~/.bashrc