#!/bin/zsh

# zsh Autosuggestions
bindkey "^ " autosuggest-accept  # Ctrl + Space
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

# BEGIN opam configuration
# This is useful if you're using opam as it adds:
#   - the correct directories to the PATH
#   - auto-completion for the opam binary
# This section can be safely removed at any time if needed.
[[ ! -r '/home/sandeepsingh/.opam/opam-init/init.zsh' ]] || source '/home/sandeepsingh/.opam/opam-init/init.zsh' > /dev/null 2> /dev/null
# END opam configuration