#!/bin/zsh

# Enable colors and change prompt:
autoload -U colors && colors

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
export HISTFILE=$XDG_STATE_HOME/zsh/history

# Commands to omit from shell history file
export HISTORY_IGNORE="(l[al.]#( *)#|cd|pwd|exit|sudo reboot|history|cd -|cd ..|..)"

# Basic auto/tab complete:
autoload -U compinit
zstyle ":completion:* menu" select cache-path $XDG_CACHE_HOME/zsh/zcompcache
zmodload zsh/complist
compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION
_comp_options+=(globdots)               # Include hidden files.

bindkey "\e[3~" delete-char

# Load the shell dotfiles, and then some:
for file in $XDG_CONFIG_HOME/sh/{aliases,functions,init}; do
	if [[ -r "$file" ]] && [[ -f "$file" ]]; then
		# shellcheck source=/dev/null
		source "$file"
	fi
done
unset file

# * ~/.zsh/extras can be used for other settings you don’t want to commit.
for file in $XDG_CONFIG_HOME/zsh/{prompt,extras,plugins}; do
	if [[ -r "$file" ]] && [[ -f "$file" ]]; then
		# shellcheck source=/dev/null
		source "$file"
	fi
done
unset file
