#!/bin/zsh

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias ls="lsd --group-dirs first"
alias ll="ls -l"
alias l="ls -lFh"     # size, show type, human readable
alias la="ls -lAFh"   # long list, show almost all, show type, human readable
alias ll="ls -l"      # long list
alias l.="ls -ld .*"

alias grep="grep --color"

# Command line head / tail shortcuts
alias -g H="| head"
alias -g T="| tail"
alias -g G="| grep"
alias -g L="| less"
alias -g M="| most"
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"
alias -g P="2>&1| pygmentize -l pytb"

alias fd="find . -type d -name"
alias ff="find . -type f -name"

alias h="history"
alias hgrep="fc -El 0 | grep"
alias help="man"
alias p="ps -f"
alias sortnr="sort -n -r"

alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"

alias vim="nvim"
alias svim="sudo vim"

alias kssh="kitty +kitten ssh"

alias userctl="systemctl --user"

alias rm="trash-put"

alias android-permissions="sudo chown -R :android /opt/android-sdk && sudo chmod -R g+w /opt/android-sdk"
alias flutter-permissions="sudo chown -R :flutter /opt/flutter && sudo chmod -R g+w /opt/flutter"