#!/bin/zsh

export XDG_CACHE_HOME=~/.cache

export ANDROID_HOME=/opt/android-sdk
export EDITOR=nvim
export QT_QPA_PLATFORMTHEME=gtk2

# Set NVIDIA Cache Path
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv

# For gnome-keyring ssh access
if [ -n "$DESKTOP_SESSION" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi