#!/bin/zsh

export ANDROID_HOME=/opt/android-sdk
export EDITOR=nvim
export QT_QPA_PLATFORMTHEME=gtk2

# For gnome-keyring ssh access
if [ -n "$DESKTOP_SESSION" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi