#!/bin/zsh

# zsh Autosuggestions
bindkey "^ " autosuggest-accept  # Ctrl + Space
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null
source /usr/share/autojump/autojump.zsh 2>/dev/null

# Prezto
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
